[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node --enable-source-maps ./dist/index.mjs"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
